# fly.toml app configuration file generated for quizzzy on 2023-11-06T06:41:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quizzzy"
primary_region = "sin"

kill_signal = "SIGTERM"
swap_size_mb = 512

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[deploy]
  release_command = "bin/rails db:prepare"
   redirect_uri_mismatch


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]